version: '2.2'
services: 
    web:
        build: .
        ports:
         - "8080:8080"

    db:
        image: mysql
        environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: bd_cabinetmedicale

        ports:
         - "3306:3306" 